# general configuration
url: ugisgroup.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/logosquare.png"
  # author will appear under the avatar (optional)
  author: "Urban and Geographic Information Systems Group"
  # tagline will appear under the title (optional)
  tagline: "A <a href='https://illinois.collegiatelink.net/organization/ugis'>registered student organization</a> at the University of Illinois at Urbana Champaign"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
